### ISSUE TITLE
Randomized delay not delaying

### ISSUE THREAD

**Issue by abenson** [leahneukirchen/snooze#11]
Seems to always fire on whatever `-S` is set to, and doesn't actually delay.

     % snooze -H 22 -M 0 -R 240 -n
     2020-09-29T22:00:00-0600 Tue  0d  0h 45m 28s
     2020-09-30T22:00:00-0600 Wed  1d  0h 45m 28s
     2020-10-01T22:00:00-0600 Thu  2d  0h 45m 28s
     2020-10-02T22:00:00-0600 Fri  3d  0h 45m 28s
     2020-10-03T22:00:00-0600 Sat  4d  0h 45m 28s

Practical example:

     % snooze -H 21 -M 31 -R 240 -v date
     randomly delaying by 169s.
     Snoozing until 2020-09-29T21:31:00-0600
     Starting execution at 2020-09-29T21:31:00-0600
     Tue 29 Sep 2020 09:31:00 PM MDT

In that case, shouldn't it fire at 21:33:49?

**Comment by abenson** [comment]
I think I have a potential fix, I'll PR it tonight.

**Comment by Duncaen** [comment]
I think this is a documentation issue, the random delay makes sure the first scheduled run doesn't happen within N (random) seconds and other than this keeps the schedule for every following run.

**Comment by leahneukirchen** [comment]
Yes, but now I wonder whats more useful?

**Comment by abenson** [comment]
Okay. What I'll do is change the wording on -R to something like "Schedule next run after -R seconds..." and then add a -J ("jitter") to randomize delay in execution after the scheduled time.  This way it won't break historical -R usage.

**Comment by abenson** [comment]
Fixed in #12 / 610e6b35ec614764770d47b5974b30fd90dce6fe
