### ISSUE TITLE
On void linux, need help

### ISSUE THREAD

**Issue by 14u2ponder** [leahneukirchen/snooze#8]
I am a little bit lost with this command. I am trying to use this to replace cron altogether since I'm using void linux.

My issue is this: while I understand the syntax to a degree, I'm not sure how I am suppose to set this up if I wanted to run a job daily.

Do I, for example: create a service in runnit and then add a line such as this:
exec snooze -H7,19 rdumpfs / /data/dump/mybox 2>&1

To the 'run' file inside /etc/sv

If it is more complicated than that, I might just have to use cron. But your help would be greatly appreciated.

**Comment by leahneukirchen** [comment]
Yes, that should work.  (Note that rdumpfs by default only supports daily backups.)

**Comment by 14u2ponder** [comment]
Hi, I got one more question. I've noticed that when I tell snooze to run every 15 minutes I get 5 entries in my dry run.
I am using rsnapshot in conjunction with this which requires me to be very specific about my number of backups.

In my case, I want snooze to run between 6 am -10 am every morning and to create exactly 4 runs per hour.
This command: **snooze -nv -d* -H 6-10 -M/15 rsnapshot hourly**  seems to produce 1 extra run.

My question is, is there a way to design a start time, and also, is it even advisable to do it every 15 minutes (could snooze get out of time so to speak so that it doesn't product the exact number I want?)
essentially I want it to run 4 times every hour from 6-10 am and without any messups.

**Comment by leahneukirchen** [comment]
Why 5 runs? I see 4 per hour, :00 :15 :30 :45

**Comment by 14u2ponder** [comment]
When I do a dry run it shows me five instances, I don't know

**Comment by leahneukirchen** [comment]
paste the output please.

**Comment by 14u2ponder** [comment]
Okay I will do that when I get home I'm at work now

**Comment by Anachron** [comment]
Afaik dry run always prints the next 5 times it will be run, that is what I remember reading from the manual at least.

**Comment by 14u2ponder** [comment]
> Afaik dry run always prints the next 5 times it will be run, that is what I remember reading from the manual at least.

This seems right.

I do have one more question though, my command -H 6-10, looks like it will run at 6PM instead of 6AM. 
I sort of figured out that the numbers are based on UTC time, so 13h is 6PM, right?
But the fact remains that I'd like it to run at 6 AM

**Comment by 14u2ponder** [comment]
I figured it out. It's correct. Issue closed.
